# SITE CONFIG
title: AlunosMaio
description: Tudo em um sรณ lugar.
github_repository: https://github.com/raincorn/alunosmaio

#SITE SETTINGS
current_version: 0.0.1-rls+zeppelin.1
git_repo: true
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
